
os:
- linux
- osx

script:
- export OS_NAME=$TRAVIS_OS_NAME
- export PROJECT_KEY=cpp-example-cmake-travis-$OS_NAME
- export CFAMILY_CAHE_PATH=${TRAVIS_HOME}/.cfamily
- bash generic-build-analyze.sh

cache:
  directories:
  - "$HOME/.sonar/cache"
  - "$HOME/.cfamily"
