version: 2.1

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:focal
    steps:
      - checkout
      - run: |
          set -euo pipefail
          export OS_NAME=linux
          export PROJECT_KEY=cpp-example-cmake-circleci-$OS_NAME
          export CFAMILY_CAHE_PATH=~/.cfamily
          sudo apt-get install -y -qq cmake gcc
          bash generic-build-analyze.sh
