name: CI

on:
  push:
    branches: [ main ]

jobs:
  basic:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64
      - name: Run a one-line script
        run: |
          export OS_NAME=$RUNNER_OS
          export PROJECT_KEY=cpp-example-cmake-github-$OS_NAME
          export CFAMILY_CAHE_PATH=.cfamily
          bash generic-build-analyze.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
